### ISSUE TITLE
Windows 8 compatibility

### ISSUE THREAD

**Issue by pdewouters** [weslly/Nettuts-Fetch#16]
I tried downloading the html5 boilerplate but it didn't work.
have you tested it on Windows 8?
Is ther esome kind of log file I can inspect?

thanks

**Comment by msuchodolski** [comment]
To fetching packages on Win8 I need to run ST3 as admin. In normal mode I can fetch files only.

**Comment by lukaszahorec** [comment]
Hi I´m getting this errors? in console always when I try fetch a file or package:

Exception in thread Thread-164:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "fetch.downloader in C:\Users\Lukáš\AppData\Roaming\Sublime Text 3\Installed Packages\Nettuts+ Fetch.sublime-package", line 44, in run
  File "fetch.downloader in C:\Users\Lukáš\AppData\Roaming\Sublime Text 3\Installed Packages\Nettuts+ Fetch.sublime-package", line 58, in download_text
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

win 8 64bit, st3
