### ISSUE TITLE
ST3 (Build 3009): plugin not working

### ISSUE THREAD

**Issue by mogilny** [weslly/Nettuts-Fetch#20]
First of all, thank you for your beautiful plugin for sublime!

Running the portable ST3, Build 3009 on a Win7 / 32-Bit I get follwoing error on the start-up in the console:

---

reloading plugin Nettuts+ Fetch.Fetch
Traceback (most recent call last):
  File "C:\Portable Apps\Sublime Text 3\sublime_plugin.py", line 70, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 854, in _load_module
  File "<frozen importlib._bootstrap>", line 981, in get_code
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Portable Apps\Sublime Text 3\Data\Packages\Nettuts+ Fetch\Fetch.py", line 248
    except (urllib2.URLError) as (e):
                                 ^
SyntaxError: invalid syntax
Unable to open /C/Portable Apps/Sublime Text 3/Data/Packages/User/Fetch.sublime-settings

---

Hope that the problem is not to hard to solve ;-)

**Comment by Abhinav1217** [comment]
Same problem with me. ST 3, Build 3010. 
I tried using package manager first, but it didn't work. 
Then i tried direct cloning from github, trick wbond mentioned in his package manager plugin. Now when type fetch in command pallet, it shows only "Fetch: Manage". Which creates a blank file "C:\Users\Abhinav\AppData\Roaming\Sublime Text 3\Packages\User\Fetch.sublime-settings", which i modified using http://piratepad.net/6L9KllaTBL to add files and packages. 

But the command pallet still doesnot show file and package option. only manage option. Will this plugin
be ported to ST3

**Comment by weslly** [comment]
It will be ported to ST3 very soon. :)

**Comment by weslly** [comment]
#23
