### ISSUE TITLE
Packages list don't work in ST2, problems yet.

### ISSUE THREAD

**Issue by LOQUILLO** [weslly/Nettuts-Fetch#36]
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 337, in run_
    return self.run(**args)
  File ".\fetch\commands\fetch_command.py", line 36, in run
  File ".\fetch\commands\fetch_command.py", line 61, in list_packages
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 5: ordinal not in range(128)

**Comment by LOQUILLO** [comment]
After of update, the problem is there, yet.
